# Generated by Django 4.2.11 on 2024-07-08 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('typedoc', models.CharField(choices=[('Nit', 'Nit'), ('CC', 'Cc')], max_length=4)),
                ('nroDoc', models.CharField(max_length=14)),
                ('gender', models.CharField(choices=[('Masculino', 'Male'), ('Femenino', 'Femi')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='DetailsPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dateexpnrodoc', models.DateTimeField()),
                ('cityexpnrodoc', models.CharField(max_length=25)),
                ('birthcity', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('streetaddress', models.TextField(max_length=255)),
                ('neighborhood', models.CharField(max_length=50)),
                ('hometype', models.CharField(choices=[('Propia', 'Propia'), ('Familiar', 'Familiar'), ('Arriendo', 'Arriendo')], max_length=15)),
                ('phonenumber', models.CharField(max_length=14)),
                ('phonenum', models.CharField(max_length=14)),
                ('cityresidence', models.CharField(max_length=100, verbose_name='Ciudad Residencia')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('familiarref', models.CharField(max_length=50, null=True)),
                ('familiaper', models.CharField(max_length=50, null=True)),
                ('famirefphone', models.CharField(max_length=14)),
                ('refperphone', models.CharField(max_length=14)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailspersons', to='creditos.person')),
            ],
            options={
                'verbose_name_plural': 'DetailsPeople',
            },
        ),
        migrations.CreateModel(
            name='DetailsEconomicActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('typeactivity', models.CharField(max_length=25)),
                ('bussinesname', models.CharField(max_length=50)),
                ('bussinessaddres', models.CharField(max_length=100)),
                ('bussinessphone', models.CharField(max_length=14)),
                ('jobposition', models.CharField(max_length=25)),
                ('startdatejob', models.DateTimeField()),
                ('contrattype', models.CharField(max_length=25)),
                ('timejobpos', models.IntegerField(null=True)),
                ('pensionfund', models.CharField(max_length=50, null=True)),
                ('startDatePF', models.DateTimeField(null=True)),
                ('rut', models.DateTimeField(null=True)),
                ('timeactivityrut', models.IntegerField(null=True)),
                ('bussinesnameind1', models.CharField(max_length=50)),
                ('nitind1', models.CharField(max_length=14)),
                ('phoneind1', models.CharField(max_length=14)),
                ('bussinesnameind2', models.CharField(max_length=50)),
                ('nitind2', models.CharField(max_length=14)),
                ('phoneind2', models.CharField(max_length=14)),
                ('bussinesnameind3', models.CharField(max_length=50)),
                ('nitind3', models.CharField(max_length=14)),
                ('phoneind3', models.CharField(max_length=14)),
                ('totalincome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentdel', models.BooleanField(default=False)),
                ('totalexpenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalassets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailseconomicactivitys', to='creditos.person')),
            ],
        ),
    ]
